FROM amazoncorretto:11.0.6

RUN yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm \
    && yum install -y mysql-community-client

WORKDIR /app
EXPOSE 8080

ENTRYPOINT ["sh", "./gradlew", "bootRun"]