version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/
      - ./tomcat/logs:/usr/local/tomcat/logs
    networks:
      - sskf_network
  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - sskf_network
  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - sskf_network
networks:
  sskf_network:
    driver: bridge